services:
  weatherapp:
    build: .
    env_file: .env
    expose:
      - "${PORT}"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    volumes:
      - /vagrant/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "443:443" # bind to all interfaces
    depends_on:
      - weatherapp
    restart: unless-stopped
